interface=
bind-interfaces
enable-ra
except-interface=lo

dhcp-range=192.168.50.10,192.168.50.100,12h
dhcp-option=3,192.168.50.1
dhcp-option=6,192.168.50.1

dhcp-range=::100,::1ff,constructor:INTERFACE,ra-stateless,64,12h
dhcp-option=option6:dns-server,[fd50:abcd:1234:1::1]


# Force all upstream DNS through VPN tunnel only
# (prevents dnsmasq itself from leaking on the upstream IF)
server=94.140.14.14@wgo_free
server=94.140.15.15@wgo_free
server=2a10:50c0::ad1:ff@wgo_free
server=2a10:50c0::ad2:ff@wgo_free

# Blocklists
addn-hosts=/etc/dnsmasq.blocklists/stevenblack.hosts
addn-hosts=/etc/dnsmasq.blocklists/swc.hosts
addn-hosts=/etc/dnsmasq.blocklists/oisd.hosts

# Logging
log-queries
log-facility=/var/log/dnsmasq.log

# Local network
domain=home
expand-hosts
cache-size=10000
neg-ttl=3600

# Security hardening
stop-dns-rebind
rebind-localhost-ok
dns-forward-max=150
