interface=
driver=nl80211

# Identity
ssid=Wi-Fight the Feeling
country_code=DE

# 5GHz AC, 80MHz channel width
hw_mode=a
channel=36
chanlist=36 40 44 48

# 802.11n
ieee80211n=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][RX-STBC12][DSSS_CCK-40][MAX-AMSDU-7935]

# 802.11ac
ieee80211ac=1
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42
vht_capab=[MAX-MPDU-11454][SHORT-GI-80][TX-STBC-2BY1][SU-BEAMFORMEE][HTC-VHT]

# Regulatory
ieee80211d=1
ieee80211h=1

# General
wmm_enabled=1
ap_isolate=0

# WPA2
auth_algs=1
wpa=2
wpa_passphrase=
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
