[Interface]
PreDown = nft flush ruleset
Table = off        # ← tells wg-quick not to touch nftables/routing
# VPN Accelerator = on
PrivateKey = OGHfJjBoyDD/tBQ44vnzbmzaQQp5MB1ZYN+UYy3CFk0=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
# No DNS = line — script owns DNS

PostUp  = ip rule add iif lo lookup main
PreDown = ip rule del iif lo lookup main

[Peer]
# NL-FREE#50
PublicKey = Jh4zc7MtYS56o+vEXKay0FpvYIZHFCmRBPAxzDzTTns=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 169.150.196.97:51820
Endpoint = [2a02:6ea0:c041:2245::10]:51820
PersistentKeepalive = 25